#    spring.web.resources.static-locations=classpath:/static/

spring:
    web:
        resources:
            static-locations: classpath:/static/
    application:
        name: peladapro
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true


server:
    port: 8080
    servlet:
        session:
            timeout: 15m

logging:
    level:
        com.peladapro: DEBUG

