#    spring.web.resources.static-locations=classpath:/static/

spring:
    web:
        resources:
            static-locations: classpath:/static/
    application:
        name: peladapro
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            idle-timeout: 30000           # 30 segundos
            max-lifetime: 300000          # 5 minutos — reinicia conexões antes do PostgreSQL matar
            keepalive-time: 150000        # 2.5 minutos — força atividade para manter conexão viva
            connection-timeout: 20000     # 20 segundos para tentar pegar conexão
            validation-timeout: 5000      # tempo limite para validar a conexão
            initialization-fail-timeout: 0
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect




server:
    port: 8080
    servlet:
        session:
            timeout: 15m

logging:
    level:
        com.peladapro: DEBUG

