#    spring.web.resources.static-locations=classpath:/static/

spring:
    web:
        resources:
            static-locations: classpath:/static/
    application:
        name: peladapro
    datasource:
        url: jdbc:postgresql://db.jknrahnytchsbwhxyqeo.supabase.co:5432/postgres
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true


server:
    port: 8080
    servlet:
        session:
            timeout: 15m

logging:
    level:
        com.peladapro: DEBUG

